---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-node
  namespace: thingsboard
spec:
  template:
    spec:
      containers:
      - name: server
        env:
        - name: REPORTS_SERVER_ENDPOINT_URL
          value: http://tb-web-report:8383